import boto3
from botocore.exceptions import ClientError


def build_session(role_arn: str, external_id: str, region_name: str = "eu-west-2") -> boto3.Session:
    """
    Assumes a customer's CloudGuardian-ReadOnly-AuditRole via STS and returns
    a boto3 Session built from the resulting temporary credentials.

    Parameters
    ----------
    role_arn     : The full ARN of the IAM role in the customer's AWS account.
                   e.g. arn:aws:iam::123456789012:role/CloudGuardian-ReadOnly-AuditRole
    external_id  : The unique per-customer External ID generated by CloudGuardian
                   at onboarding. Must match the value baked into the customer's
                   IAM role trust policy.
    region_name  : AWS region for the returned session. Defaults to eu-west-2.

    Returns
    -------
    boto3.Session with temporary credentials scoped to the customer's account.

    Raises
    ------
    ValueError   : If role_arn or external_id are missing.
    RuntimeError : If STS AssumeRole fails (wrong ARN, wrong External ID,
                   role does not exist, or insufficient permissions).
    """

    if not role_arn or not external_id:
        raise ValueError("Both role_arn and external_id are required.")

    sts = boto3.client("sts", region_name=region_name)

    try:
        response = sts.assume_role(
            RoleArn=role_arn,
            RoleSessionName="CloudGuardianAuditSession",
            ExternalId=external_id,
            # Temporary credentials are valid for 1 hour (3600s) — the default.
            # Scans complete well within this window; no refresh logic needed.
            DurationSeconds=3600,
        )
    except ClientError as e:
        error_code = e.response["Error"]["Code"]
        error_msg = e.response["Error"]["Message"]
        raise RuntimeError(
            f"STS AssumeRole failed [{error_code}]: {error_msg}. "
            f"Check that the Role ARN is correct, the External ID matches "
            f"the trust policy, and that the CloudGuardian platform account "
            f"has permission to assume this role."
        ) from e

    creds = response["Credentials"]

    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
        region_name=region_name,
    )